### ISSUE TITLE
Puppet output is not visible on the console while running the build process

### ISSUE THREAD

**Issue by imesh** [abhishek0198/wso2dockerfiles-test-framework#12]
Currently, the Puppet output is not visible on the console while running the Docker image build process using Puppet provisioning. IMO it would be better to print this to the console by default and provide a configurable option to switch it off if needed. Otherwise, users would not be able to see the actual process while running the tests. Thanks!

**Comment by abhishek0198** [comment]
You can now use "silent_build_output" to configure it, by default it is set to false so you will see the complete build output. 

Fixed here:
https://github.com/abhishek0198/wso2dockerfiles-test-framework/commit/47c29342dfe487531be150f7fe940349b63db590
