### ISSUE TITLE
Configuration parameter carbon_server_ip is not self readable

### ISSUE THREAD

**Issue by imesh** [abhishek0198/wso2dockerfiles-test-framework#14]
What would be the purpose of carbon_server_ip configuration parameter? 

I guess it is for specifying the container host IP address. However, what name implies is that it should specify the carbon server IP address, which in this case would be the container IP address. Therefore I think the name used for this configuration parameter is misleading.

**Comment by abhishek0198** [comment]
This parameter has been changed to docker_container_ip.
