### ISSUE TITLE
Improve log messages

### ISSUE THREAD

**Issue by imesh** [abhishek0198/wso2dockerfiles-test-framework#18]
Maybe the word "up" is unnecessary in the following log message:
2016/08/17 23:35:05 main.go:151: Starting test setup up

As I found, tests run even after printing the below log message. Therefore the meaning of the message might not be correct. Maybe, we can change this to "Successfully started the container". WDYT?
2016/08/17 23:35:54 common-utils.go:66: Successfully ran docker image.

**Comment by abhishek0198** [comment]
@imesh Agreed, will change the logging to reflect these.

**Comment by abhishek0198** [comment]
Fixed in commit:
https://github.com/abhishek0198/wso2dockerfiles-test-framework/commit/762e2329a5a6a423f023b0f470ceee51840c857c
