### ISSUE TITLE
Test fails saying 'Errors founds in carbon server logs' even though there are no error logs in wso2carbon.log 

### ISSUE THREAD

**Issue by Thanu** [abhishek0198/wso2dockerfiles-test-framework#20]
I have used the test framework to check the flow of building and running WSO2 BPS 3.5.1 docker image. According to the framework log[1], the test fails because of an error in the carbon server log. But when I check the carbon server log, there were no ERROR logs and it has 'error' as part of a word in line[2].

For this scenario, we should not make the test to be failed. I think instead of simply grepping the 'error' word as in[[3]](https://github.com/abhishek0198/test-framework/blob/master/common/common-utils.go#L169), we should grep the ERROR logs.

[1].
**2016/08/18 14:21:20 common-utils.go:166: Checking Carbon server logs for any errors
2016/08/18 14:21:20 docker-utils.go:105: Successfully copied carbon server logs from docker container
2016/08/18 14:21:20 common-utils.go:173: Errors founds in carbon server logs, please check them under wso2bps3.5.1logs**

[2]. 
TID: [-1234] [] [2016-08-18 08:51:15,701]  **INFO** {org.springframework.beans.factory.support.DefaultListableBeanFactory} -  Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@38d281d4: defining beans [cxf,org.apache.cxf.bus.spring.BusWiringBeanFactoryPostProcessor,org.apache.cxf.bus.spring.Jsr250BeanPostProcessor,org.apache.cxf.bus.spring.BusExtensionPostProcessor,deploymentService,runtimeService,queryRuntimeService,historyService,formService,processDefinitionService,identityService,managementService,statsService,authenticationBean,exceptionHandlerBean,**error**HandlerBean,jacksonBean]; root of factory hierarchy {org.springframework.beans.factory.support.DefaultListableBeanFactory}

**Comment by abhishek0198** [comment]
@Thanu Fixed here
https://github.com/abhishek0198/wso2dockerfiles-test-framework/commit/ecb8dec5c7a0553f36a21b4a7c87cd0cf9a0adb9
