### ISSUE TITLE
A Makefile is needed for managing the build process

### ISSUE THREAD

**Issue by imesh** [abhishek0198/wso2dockerfiles-test-framework#4]
We might need to add a Makefile for automating the build process.

**Comment by abhishek0198** [comment]
@imesh build process is very simple now, requires only two commands:
go get -d github.com/abhishek0198/test-framework  
go build  

Do you still think, we need a Makefile?

**Comment by imesh** [comment]
That's great! The purpose of the Makefile is to download the dependencies automatically and build. Does that happen with go build?

**Comment by abhishek0198** [comment]
This is no longer needed since all the dependencies are automatically fetched by go get. Feel free to re-open if you think otherwise.
